name: Android CI

on:
  pull_request:
    branches: [develop] # Multiple branches ex. [master, staging, develop]
  push:
    branches: [staging]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build with Gradle
        run: |
          ./gradlew build

  build-apk-debug:
    needs: [build-android]
    runs-on: ubuntu-latest
    if: contains('
      refs/heads/staging
      ', github.ref)
    steps:
      - uses: actions/checkout@v2
      - name: Build Android Debug
        run: |
          ./gradlew assembleDebug
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-debug.apk
          path: mobile/build/outputs/apk/debug/mobile-debug.apk
